### ISSUE TITLE
Remember Events Between Edits and Visits

### ISSUE THREAD

**Issue by sterlinm** [ngduc/life-calendar#3]
Very fun! Every time I click on the `Events` button it reverts to the default text, even if I've already modified it. It would be nice if it remembered previous edits and even better if it remembered them between page visits.

I was going to mention the WBW article but I see that this was inspired by that. It would be fun if there was a theme that styled the page similar to that article.

**Comment by ngduc** [comment]
Thanks @sterlinm !
It should be fixed now: (this used to work but I broke it :) )
https://life-calendar-in-weeks.vercel.app/

I'm working on the WBW article's layout, it will be there soon.

**Comment by sterlinm** [comment]
Awesome thanks!
